### ISSUE TITLE
Tor trouble after last update

### ISSUE THREAD

**Issue by grimnir** [sqlmapproject/sqlmap#1208]
Good day
After last update got message  "it seems that Tor is not properly set. Please try using options '--tor-type' and/or '--tor-port' "  when using same option ,which worked before --tor --check-tor --tor-type=SOCKS5 --tor-port=9150
I use my old backup to compare, when tor option dont working and found this reason in file
\lib\request\connect.py  ,line numbers  854,858,864,335-339 
Can you please fix this? Thank you

**Comment by stamparm** [comment]
Not sure what's the problem in those lines?

**Comment by grimnir** [comment]
335-339  old version( working)
 headers[HTTP_HEADER.ACCEPT_ENCODING] = HTTP_ACCEPT_ENCODING_HEADER_VALUE if kb.pageCompress else "identity"
            headers[HTTP_HEADER.HOST] = host or getHostHeader(url)

new
            if HTTP_HEADER.HOST not in headers:
                headers[HTTP_HEADER.HOST] = getHostHeader(url)

            if HTTP_HEADER.ACCEPT_ENCODING not in headers:
                headers[HTTP_HEADER.ACCEPT_ENCODING] = HTTP_ACCEPT_ENCODING_HEADER_VALUE if kb.pageCompress else "identity"

851-865(old)
                        name = name.strip()
                        if name in keywords:
                            name = "%s%s" % (name, EVALCODE_KEYWORD_SUFFIX)
                        value = urldecode(value, convall=True, plusspace=(item==post and kb.postSpaceToPlus))
                        evaluateCode("%s=%s" % (name, repr(value)), variables)

            if cookie:
                for part in cookie.split(conf.cookieDel or DEFAULT_COOKIE_DELIMITER):
                    if '=' in part:
                        name, value = part.split('=', 1)
                        name = name.strip()
                        if name in keywords:
                            name = "%s%s" % (name, EVALCODE_KEYWORD_SUFFIX)
                        value = urldecode(value, convall=True)
                        evaluateCode("%s=%s" % (name, repr(value)), variables)


new
                        name = re.sub(r"[^\w]", "", name.strip())
                        if name in keywords:
                            name = "%s%s" % (name, EVALCODE_KEYWORD_SUFFIX)
                        value = urldecode(value, convall=True, plusspace=(item==post and kb.postSpaceToPlus))
                        variables[name] = value

            if cookie:
                for part in cookie.split(conf.cookieDel or DEFAULT_COOKIE_DELIMITER):
                    if '=' in part:
                        name, value = part.split('=', 1)
                        name = re.sub(r"[^\w]", "", name.strip())
                        if name in keywords:
                            name = "%s%s" % (name, EVALCODE_KEYWORD_SUFFIX)
                        value = urldecode(value, convall=True)
                        variables[name] = value

can`t find whats wrong here ,but in new version tor option not working

**Comment by stamparm** [comment]
![1](https://cloud.githubusercontent.com/assets/921555/6846411/8d435994-d3be-11e4-9d3c-cddd749dc409.png)

But it seems ok at my side.

**Comment by grimnir** [comment]
Ok, i`ll try to use another version ,cos my 1.0-dev-nongit-20150326

**Comment by grimnir** [comment]
Ok, now update to last version, and here some strange-
if i wrote  like here down all working great , but just add --level=5   then got message 
[CRITICAL] it seems that Tor is not properly set. Please try using options '--tor-type' and/or '--tor-port'

C:\Users\linux>python.exe "C:\Python\App\sql\sqlmap.py" -u "http://testphp.vulnweb.com/artists.php?artist=1*"  --tor --check-tor --tor-type=SOCKS5 --tor-port=9150  --eta  --random-
agent --threads=14!
         _
 ___ ___| |_____ ___ ___  {1.0-dev-nongit-20150326}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and fed
eral laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 14:09:23

[14:09:23] [WARNING] increasing default value for option '--time-sec' to 10 because switch '--tor' was provided
[14:09:23] [INFO] setting Tor SOCKS proxy settings
[14:09:23] [INFO] fetched random HTTP User-Agent header from file 'C:\Python\App\sql\txt\user-agents.txt': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_1; en-US) AppleWebKit/532
.2 (KHTML, like Gecko) Chrome/4.0.222.4 Safari/532.2'
[14:09:23] [INFO] checking Tor connection
[14:09:26] [INFO] Tor is properly being used
custom injection marking character ('*') found in option '-u'. Do you want to process it? [Y/n/q]
[14:09:36] [INFO] testing connection to the target URL
[14:09:37] [INFO] testing if the target URL is stable. This can take a couple of seconds
[14:09:38] [INFO] target URL is stable
[14:09:38] [INFO] testing if URI parameter '#1*' is dynamic
[14:09:39] [INFO] confirming that URI parameter '#1*' is dynamic
[14:09:40] [INFO] URI parameter '#1*' is dynamic
[14:09:41] [INFO] heuristic (basic) test shows that URI parameter '#1*' might be injectable (possible DBMS: 'MySQL')
[14:09:41] [INFO] testing for SQL injection on URI parameter '#1*'
[14:09:44] [WARNING] user aborted during detection phaseto skip test payloads specific for other DBMSes? [Y/n]
how do you want to proceed? [(S)kip current test/(e)nd detection phase/(n)ext parameter/(c)hange verbosity/(q)uit]

**Comment by stamparm** [comment]
What is strange here?

**Comment by grimnir** [comment]
this
but just add --level=5 then got message
[CRITICAL] it seems that Tor is not properly set. Please try using options '--tor-type' and/or '--tor-port'
and this stop working

**Comment by stamparm** [comment]
Can you please update to the current version. I've committed maybe a related patch ten minutes ago.

**Comment by grimnir** [comment]
ok, still get error if use with  option --level=5  . If use --level=4 all working great.
python.exe "C:\Python\App\sql\sqlmap.py" -u "testphp.vulnweb.com/artists.php?artist=1*" --tor --check-tor --tor-type=SOCKS5 --tor-port=9150 --level=5
[15:36:42] [WARNING] increasing default value for option '--time-sec' to 10 because switch '--tor' was provided
[15:36:42] [INFO] setting Tor SOCKS proxy settings
[15:36:42] [INFO] checking Tor connection
[15:36:46] [INFO] heuristics detected web page charset 'ascii'
[15:36:47] [CRITICAL] it seems that Tor is not properly set. Please try using options '--tor-type' and/or '--tor-port'
